### ISSUE TITLE
Helicopter won't go away

### ISSUE THREAD

**Issue by UsernameIsToLon** [sharkster91/ExpandedHelicopterEvents#54]
After appearing and shouting warnings to get off the street, exceptions were thrown in console and the helicopter does not seem to go away anymore. (1day there now)

```
ERROR: General     , 1643674805012> 106.256.946> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: maxRange of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1643674805012> 106.256.946> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: maxRange of non-table: null
        at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
        at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
        at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
        at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
        at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
        at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
        at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
        at zombie.Lua.Event.trigger(Event.java:64)
        at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:88)
        at zombie.gameStates.IngameState.updateInternal(IngameState.java:1673)
        at zombie.gameStates.IngameState.update(IngameState.java:1367)
        at zombie.network.GameServer.main(GameServer.java:890)
LOG  : General     , 1643674805013> 106.256.947> -----------------------------------------
STACK TRACE
-----------------------------------------
function: setOrUpdate -- file: ExpandedHelicopter11_EventMarkerHandler.lua line # 34
function: update -- file: ExpandedHelicopter01e_MainUpdate.lua line # 187
function: updateAllHelicopters -- file: ExpandedHelicopter01e_MainUpdate.lua line # 285
```

**Comment by ChuckTheSheep** [comment]
Should be fixed with yesterday's hotfix.

**Comment by ProfanedBane** [comment]
Haven't had a chance to check the logs for you but I can confirm this is still an issue with the current build (1st Feb on workshop).

Usual format is events happen as they should, but never terminate.
- Bomb siren starts and jets/bombs drop, siren stays on indefinitely
- Shooter copter appears and shoots as expected, flies away to a certain point but has the sound persist
- Supply copter appears and drops supplies, sound remains in the distance indefinitely (haven't checked if the copter itself is there)
